---
tests: ["test", "molecule", "docker-compose.test.yml", "*.phpt"]
documentation: ["*.md", "*.rst", "*.txt", "LICENSE"]
configuration: [".github/", ".gitignore", ".gitattributes", ".vscode/", ".devcontainer/", ".editorconfig", ".yamllint.yml", ".ansible-lint"]
terraform: ["terraform/", "*.tf", "*.lock.hcl"]
ansible: ["ansible/", "ansible.cfg", ".ansible-lint"]
docker: ["Dockerfile", "docker-compose.yml", "docker-compose.test.yml"]
python: ["*.py", "requirements.txt", "Pipfile", "Pipfile.lock"]
php: ["*.php", "*.phpt", "composer.json", "composer.lock"]
github: [".github/"]
github_actions: [".github/workflows/"]
vscode: [".vscode/"]
policy: [".github/ISSUE_TEMPLATE", ".github/PULL_TEMPLATE", "LICENSE", "SECURITY.md"]
# Pull request has files in it that it shouldn't!
broken: ["*.pem", "*.jks"]
