---
tests: ["test", "molecule", "docker-compose.test.yml", "*.phpt"]
documentation: ["*.md", "*.rst", "*.txt", "LICENSE"]
configuration: [".github/settings", ".gitignore", ".gitattributes", ".vscode/", ".devcontainer/", ".editorconfig", ".yamllint.yml", ".pymarkdown.yml", "tox.ini", ".ansible-lint"]
terraform: ["terraform/", "*.tf", "*.lock.hcl"]
ansible: ["ansible/", "ansible.cfg", ".ansible-lint"]
docker: ["Dockerfile", "docker-compose.yml", "docker-compose.test.yml", ".dockerignore"]
python: ["*.py", "requirements.txt", "Pipfile", "Pipfile.lock", "pyproject.toml", "setup.cfg", "setup.py", "tox.ini"]
php: ["*.php", "*.phpt", "composer.json", "composer.lock"]
dependabot: [".github/dependabot.yml"]
devcontainer: [".devcontainer/", "devcontainer.json", "devcontainer-feature.json", "scenarios.json"]
github: [".github/"]
github_actions: [".github/actions/", "action.yml", "action.yaml", "action.json"]
github_workflows: [".github/workflows/"]
github_wiki: [".github/wiki/"]
github_templates: [".github/ISSUE_TEMPLATE", ".github/PULL_TEMPLATE"]
github_annotations: [".github/annotations/"]
vscode: [".vscode/"]
policy: [".github/ISSUE_TEMPLATE", ".github/PULL_TEMPLATE", "LICENSE", "SECURITY.md"]
security: ["SECURITY.md"]
tex: ["*.tex", "*.bib"]
debian: ["debian/"]
java: ["*.java", "pom.xml"]
selinux: ["*.te", "*.if", "*.fc", "*.if", "*.cil", "*.pp", "*.fc", "*.if", "*.cil", "*.pp"]
# Pull request has files in it that it shouldn't!
broken: ["*.pem", "*.jks", "*.key", "*.crt", "*.cer", "*.p12", "*.pfx", "*.p7b", "*.p7c", "*.p7m", "*.p7r", "*.p7s", "*.p8"]
