---
tests: ["test"]
docs: ["*.md", "*.rst", "docs/", "LICENSE"]
config: [".github/", ".gitignore", ".vscode/", ".devcontainer/", ".editorconfig", ".yamllint.yml", ".ansible-lint"]
terraform: ["terraform/", "*.tf", "*.lock.hcl"]
ansible: ["ansible/", "ansible.cfg"]
docker: ["Dockerfile", "docker-compose.yml"]
python: ["*.py", "requirements.txt"]
php: ["*.php", "composer.json", "composer.lock"]
github: [".github/"]
github_actions: [".github/workflows/"]
# Pull request has files in it that it shouldn't!
broken: ["*.pem", "*.jks"]
