---
name: Ansible Role Release

on:
  workflow_call:
    secrets:
      token:
        description: "Ansible Galaxy Access Token"
        required: true

jobs:
  publish:
    name: Release to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v1
        with:
          api_key: ${{ secrets.token }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release Notes
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
