---
name: Container Release

on:
  workflow_call:
    inputs:
      registry:
        description:
        default: "ghcr.io"
        required: false
        type: "string"
      username:
        description: "Registry username"
        required: true
        type: "string"
      password:
        description: "Registry password/token"
        required: true
        type: "string"

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  container-release:
    # Ensure test job passes before pushing image.
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Packages Container registry
        uses: docker/login-action@v1 
        with:
          registry: "${{ inputs.registry }}"
          username: "${{ inputs.username }}"
          password: "${{ inputs.password }}"

      - name: Container Reference Name
        id: container_ref
        run: |
          # Strip git ref prefix from version
          NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,; s/^v//')
          # Use Docker `latest` tag convention
          [ "$NAME" == "master" ] && NAME=latest
          # Expose variables
          echo "ref_name=$NAME" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.ref_name }}
