---
name: Linting

on:
  workflow_call:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 flake8-bugbear flake8-docstrings flake8-pylint flake8-github-annotations pymarkdownlnt yamllint

      - name: Lint with yamllint
        run: |
          yamllint . --format github

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --format github
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --format github

      - name: Add problem matcher
        run: |
          echo "::add-matcher::.github/annotations/pymarkdown-problem-matcher.json"

      - name: Lint with pymarkdownlint
        run: |
          pymarkdownlnt scan `git ls-files '*.md' ':!:*TEMPLATE/*md'`
