---
name: Reusable Stale Workflow

on:
  workflow_call:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale-reuasable:
    name: Close stale issues and PRs
    runs-on: ubuntu-24.04

    steps:
      - name: Run GitHub Actions Stale
        uses: actions/stale@v9
        with:
          days-before-stale: 180
          days-before-close: 90
          exempt-all-milestones: true
          exempt-issue-labels: security
          exempt-pr-labels: dependencies, security
          stale-issue-label: stale
