---
name: Close stale issues and pull-requests

on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: GitHub Action Stale
    uses: hspaans/.github/.github/workflows/reusable-stale.yml@master
